name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  security-events: write

jobs:
  # =========================
  # BUILD (MULTI-OS MATRIX)
  # =========================
  build:
    name: Build
    runs-on: ubuntu-latest

    #    strategy:
    #      matrix:
    #        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Get source code
      - uses: actions/checkout@v4

      # Install Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # Setup Gradle + cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Fix permission (Linux/macOS only)
      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      # Build project (Windows uses gradlew.bat automatically)
      - name: Build
        run: ./gradlew build

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: kroemvandy/demo-app
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kroemvandy/demo-app:latest

  # =========================
  # DEPENDENCY GRAPH (SAFE)
  # =========================
#  dependency-submission:
#    name: Dependency Graph
#    if: github.event_name == 'push'   # 🔥 prevents permission error
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: "17"
#          distribution: "temurin"
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#
#      - name: Submit dependency graph
#        uses: gradle/actions/dependency-submission@v4